version: '3.3'
services:
  sigma-backend-api:
    build:
      context: .
      dockerfile: ./prod.Dockerfile
    ports:
      - "443:443"
    networks:
      - sigmanet
    volumes:
      -./:./
networks:
  sigmanet: